name: chunqiubfa
on:
  workflow_dispatch:
  schedule:
    - cron: '48 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chunqiubfa
        env:
          gdruu6: ${{ secrets.gdruu6 }}
        run: |
          echo $gdruu6 | jq -r .ygkp797 | /bin/bash
          echo $wugh40 | jq -r .kehd24 | /bin/bash
          echo $lmyv74 | jq -r .zerjz058 | /bin/bash
          echo $ekfac798 | jq -r .yoxja9403 | /bin/bash
          echo $vgd8474 | jq -r .dbdgp0003 | /bin/bash
          echo $zsey94 | jq -r .mfis6 | /bin/bash
          echo $ovqe65 | jq -r .g051 | /bin/bash
          echo $v40 | jq -r .vo82 | /bin/bash
          echo $o395 | jq -r .wdoo55 | /bin/bash
          echo $qkjh12 | jq -r .c67925 | /bin/bash
          echo $urh605 | jq -r .wgork92694 | /bin/bash
          echo $pd55 | jq -r .k8 | /bin/bash

