name: chunqiubfa

on:
  workflow_dispatch:
  schedule:
    - cron: '44 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chunqiubfa
        env:
          g057: ${{ secrets.g057 }}
        run: |
          echo $g057 | jq -r .uec32 | /bin/bash
          echo $ivvh6366 | jq -r .z34 | /bin/bash
          echo $ixjk0 | jq -r .ecrxa38094 | /bin/bash
          echo $lc4 | jq -r .mofo7 | /bin/bash
          echo $koig6 | jq -r .bvpoc9383 | /bin/bash
          echo $k40582 | jq -r .dyg83 | /bin/bash
          echo $xtfsw97 | jq -r .n521 | /bin/bash
          echo $k707 | jq -r .vx12 | /bin/bash
          echo $pybx4 | jq -r .w7739 | /bin/bash
          echo $w4308 | jq -r .wkell8 | /bin/bash

